var ExtensionCreateAccount=function(l,e){e||(e={});Dialog.call(this,l,Object.assign(e,{dynamicHeight:!1,responsive:!1,buttonAlign:this.CENTER_ALIGN,largeButtons:!0,buttonsInsideContent:!0,title:Strings.translateString("Create Account"),hideHeaderTitle:!0,hideBackButton:!0}))};ExtensionCreateAccount.prototype=Object.create(CreateAccountDialog.prototype);ExtensionCreateAccount.prototype.constructor=ExtensionCreateAccount;
(function(){function l(){b.inputFields.email.onChange(function(c){c&&n(c,function(a){b.inputFields.email.validate({response:a})})})}function e(){b.inputFields.password.onChange(function(c){c&&b.inputFields.password.validate({password:b.inputFields.password.getValue(),email:b.inputFields.email.getValue()})});b.inputFields.password.getElement().keyup(function(c){b.inputFields.password.validate({password:b.inputFields.password.getValue(),email:b.inputFields.email.getValue()},!0)})}function p(){b.inputFields.reconfirm.onChange(function(c){c&&
b.inputFields.reconfirm.validate({reconfirm:b.inputFields.reconfirm.getValue(),password:b.inputFields.password.getValue()})})}function q(){b.inputFields.reminder.onChange(function(c){c&&b.inputFields.reminder.validate({reminder:b.inputFields.reminder.getValue(),password:b.inputFields.password.getValue()})})}function n(b,a){bg.LPServer.textRequest({type:"GET",url:"create_account.php",CSRFToken:!1,data:{username:b,check:"avail",mistype:1},success:a,error:a})}function g(c,a){return function(d,f){var e=
!1;a&&(b.clearError(c),e=a.validate(d,function(a){b.addError(c,a)},f));return e}}function r(){if(!b.inputFields.email.fieldValidator){var c=LPTools.createElement("a",{"class":"pull-right recovery-link",href:"https://lastpass.com/forgot.php",target:"_blank"},Strings.translateString("Recovery Help")),a=LPTools.createElement("p",null,Strings.translateString("Email address already in use "));a.appendChild(c);c=new FieldValidator({summary:{id:"validatorSummaryEmail",parentEl:$("label[for='createAccountEmail'].error-summary"),
labelEl:$("label[for='createAccountEmail'].validator-label")},validators:[{id:"403",errorMsg:LPTools.createElement("p",null,Strings.translateString("You've made too many attempts, wait 5 minutes and try again.")),isValid:function(a){return!(a.response.status&&403===a.response.status)}},{id:"emailUsed",errorMsg:a,isValid:function(a){return"no"!==a.response}},{id:"emailInvalid",errorMsg:LPTools.createElement("p",null,Strings.translateString("Make sure to use a real email address")),isValid:function(a){return"ok"===
a.response&&0!==a.response.indexOf("mistype:")&&"emailinvalid"!==a.response}}]});b.inputFields.email.validate=g("email",c);b.inputFields.email.fieldValidator=c}}function t(){if(!b.inputFields.termsAndConditions.fieldValidator){var c=new FieldValidator({summary:{id:"validatorSummaryTermsAndConditions",parentEl:$("label[for='termsAndConditions'].error-summary"),labelEl:$("label[for='createAccountEmail'].validator-label")},validators:[{id:"termsNotChecked",errorMsg:LPTools.createElement("p",null,Strings.translateString("Please agree to the Terms and Conditions")),
isValid:function(a){return!0===a.termsAndConditions}}]});b.inputFields.termsAndConditions.validate=g("termsAndConditions",c);b.inputFields.termsAndConditions.fieldValidator=c}}function u(){if(!b.inputFields.password.fieldValidator){var c=new FieldValidator({summary:{id:"validatorSummaryPassword",parentEl:$("label[for='createAccountDialogPassword'].error-summary"),labelEl:$("label[for='createAccountDialogPassword'].validator-label"),errorMsg:LPTools.createElement("p",null,Strings.translateString("Sorry, your password is invalid"))},
listParentEl:$("#mpValidators"),isPopup:b.data.isPopup,validators:[{id:"passwordLength",name:LPTools.createElement("p",null,Strings.translateString("At least 8 characters long")),errorMsg:LPTools.createElement("p",null,Strings.translateString("Master password must be at least 8 characters")),isValid:function(a){return!0===(a.password&&8<=a.password.length)}},{id:"passwordSameAsEmail",name:LPTools.createElement("p",null,Strings.translateString("Not your email")),errorMsg:LPTools.createElement("p",
null,Strings.translateString("Master password shouldn\u2018t contain your email")),isValid:function(a){return!0===(a.password&&a.email&&-1===a.password.toLowerCase().indexOf(a.email.toLowerCase())&&-1===a.email.toLowerCase().indexOf(a.password.toLowerCase()))}},{id:"easyPassword",name:LPTools.createElement("p",null,Strings.translateString("Not easily guessable")),errorMsg:LPTools.createElement("p",null,Strings.translateString("That\u2018s in the top 100 most-used passwords")),isValid:function(a){return!0===
(a.password&&!a.password.match(/^password\d{0,3}$/i)&&!a.password.match(/^lastpass\d{0,3}$/i)&&!a.password.match(/^.{0,7}$/)&&"12345678"!==a.password&&"123456789"!==a.password&&"1234567890"!==a.password&&"lastpass.com"!==a.password&&"qwertyuiop"!==a.password&&"abcd1234"!==a.password)}}]});b.inputFields.password.validate=g("password",c);b.inputFields.password.fieldValidator=c}}function v(){if(!b.inputFields.reconfirm.fieldValidator){$("#twinsies").hide();var c=new FieldValidator({summary:{id:"validatorSummaryReconfirm",
parentEl:$("label[for='createAccountDialogConfirmPassword'].error-summary"),labelEl:$("label[for='createAccountDialogConfirmPassword'].validator-label, #twinsies")},validators:[{id:"reconfirmSameAsPassword",name:LPTools.createElement("p",null,Strings.translateString("Reconfirm same as password")),errorMsg:LPTools.createElement("p",null,Strings.translateString("Make sure this matches your master password")),isValid:function(a){return!0===(a.reconfirm&&a.password===a.reconfirm)}}]});b.inputFields.reconfirm.validate=
g("reconfirm",c);b.inputFields.reconfirm.fieldValidator=c}}function w(){if(!b.inputFields.reminder.fieldValidator){var c=new FieldValidator({summary:{id:"validatorSummaryReminder",parentEl:$("label[for='createAccountReminder'].error-summary"),labelEl:$("label[for='createAccountReminder'].validator-label")},validators:[{id:"reminderNotPassword",name:LPTools.createElement("p",null,Strings.translateString("Reminder doesn\u2018t contain password")),errorMsg:LPTools.createElement("p",null,Strings.translateString("Reminder can\u2018t contain your master password")),
isValid:function(a){return!(a.password&&-1!==a.reminder.toLowerCase().indexOf(a.password.toLowerCase()))}}]});b.inputFields.reminder.validate=g("reminder",c);b.inputFields.reminder.fieldValidator=c}}var b,k,m,h;ExtensionCreateAccount.prototype.initialize=function(c){CreateAccountDialog.prototype.initialize.apply(this,arguments);$(".meterContainer").remove();this.inputFields.password.getElement().LP_addPasswordMeter(this.inputFields.email.getElement(),!this.data.isPopup);b=this;(function(a){var d=
c.find(".buttonContent"),f=c.find(".buttons").detach();d.append(f);a.data.isPopup?(new FieldToolTip({parentEl:c,isPopup:a.data.isPopup,arrow:new lpArrow({$parentEl:$("#helpContainer")})}),d=c.find("#mpEntry .buttons.centerButtons"),f=LPTools.createElement("button","nbtn wbtn",Strings.translateString("Back")),d.prepend(f),f=c.find("#mpEntry .nbtn.wbtn"),f.bind("click",function(a){b.showPreviousView()}),h="2.0"):(new FieldToolTip({parentEl:c,isPopup:a.data.isPopup}),m=new EmailToolTip({toolTipEl:c.find("#mpCurrentEmail"),
parentEl:$("body"),emailField:b.inputFields.email,backActionFn:function(){b.showPreviousView()}}),$("body").addClass("login-background"),h="1.0");c.find("#signInBtn").bind("click",function(b){b.preventDefault();bg.sendLpImprove("viewloginform");a.data.isPopup?ExtensionDropdown.openDialog("loginTab"):dialogs.loginSimple.open({isPopup:!1});a.close(!0)});r();t();l();e();p();q();k=new BackgroundOverlay({parentEl:$("body")});b.setDynamicHeight()})(this)};ExtensionCreateAccount.prototype.setNextView=function(b){Dialog.prototype.setNextView.apply(this,
arguments);m&&m.toggle(0<b);bg.sendLpImprove("viewregform",{currentPage:0===this.currentViewIndex?"email":"mpw",version:h})};ExtensionCreateAccount.prototype.close=function(b){b?Dialog.prototype.close.apply(this,arguments):function(a){LPTools.getOption(a.data,"showcloseconfirm",!0)?(k.show(),dialogs.confirmation.open({title:"LastPass",text:Strings.translateString("Do you really want to quit?  You cannot use LastPass without creating an account."),closeHandler:function(){k.hide()},handler:function(){a.close(!0)}})):
a.close(!0)}(this)};ExtensionCreateAccount.prototype.clearError=function(b){(b=this.inputFields[b])&&b.clearErrors()};ExtensionCreateAccount.prototype.addError=function(b,a){var c=this.inputFields[b];c&&(c._errors.push(a),c.clearErrors=function(){this._errors=[];c._errorElement&&c._errorElement.remove();this._errorElement=null})};ExtensionCreateAccount.prototype.validate=function(c,a){if(0===this.currentViewIndex)n(c.email,function(d){(d=b.inputFields.email.validate({response:d}))&&(d&=b.inputFields.termsAndConditions.validate(c));
a&&a(d)});else if(this.currentViewIndex===this.views.length-1){var d=b.inputFields.password.validate(c),d=d&b.inputFields.reconfirm.validate(c),d=d&b.inputFields.reminder.validate(c);a&&a(d)}};ExtensionCreateAccount.prototype.submit=function(){try{var c=this.getData();this.validate(c,function(a){if(a)b.getNextViewButton()===b.nextButton&&b.views&&b.currentViewIndex<b.views.length-1?(u(),v(),w(),b.setNextView(b.currentViewIndex+1),b.setDynamicHeight()):(bg.sendLpImprove("completedregform",{version:h}),
b.handleSubmit(c,this.data),b.data.isPopup&&b.close(!0));else{a=[];for(var d in b.inputFields)b.inputFields.hasOwnProperty(d)&&b.inputFields[d].fieldValidator&&(a=a.concat(b.inputFields[d].fieldValidator.getValidationList()));d=a.join(",");a={errorlist:d,version:h};b.inputFields.reminder&&""!==b.inputFields.reminder.getValue()&&(a.isReminder=!0);0<d.length&&(a.currentPage=0===b.currentViewIndex?"email":"mpw",bg.sendLpImprove("validationregform",a))}})}catch(a){LPPlatform.logException(a)}};ExtensionCreateAccount.prototype.showInProcessOverlay=
function(){k.show(!0)}})();
