var ExtensionLoginDialog=function(a){LoginDialog.call(this,a,{closeButtonEnabled:!1});this.populatedSavedLogin=!1;(function(c){c.savedLoginCallback=function(b){for(var a=[],k=function(b){return function(a){bg.delete_saved_login(b);a.stopPropagation();a.preventDefault();for(a=0;a<c.data.savedLogins.length;a++)if(c.data.savedLogins[a].username===b){c.data.savedLogins.splice(a,1);break}c.inputFields.email.removeValue(b);c.inputFields.email.inputObject.input.val("");c.inputFields.password.setValue("");
c.inputFields.email.updateDropdown("");c.inputFields.email.clearHint()}},d=0,f=b.length;d<f;++d){var e=b[d].username,g=LPTools.createElement("li",{dropdownValue:e},"");g.appendChild(LPTools.createElement("span",{"class":"dropdownText"},e));var h=LPTools.createElement("img",{src:"images/vault_4.0/Close_x.png","class":"ddl-remove"});LPPlatform.addEventListener(h,"mousedown",k(e));g.appendChild(h);a.push({value:e,label:e,element:g})}c.inputFields.email.setOptions(a);0<b.length?(a=b[0],c.data.savedLogins=
b,c.inputFields.email.setValue(a.username),c.inputFields.password.focus()):c.inputFields.email.focus()};c.browserPasswordManagerCallback=function(){$("#loginDialogDisablePasswordManagerContainer").show();c.inputFields.disablePasswordManager.setValue(bg.Preferences.get("disableffpwasked"))}})(this)};ExtensionLoginDialog.prototype=Object.create(LoginDialog.prototype);ExtensionLoginDialog.prototype.constructor=ExtensionLoginDialog;
(function(){ExtensionLoginDialog.prototype.populateSavedLogin=function(a){this.inputFields.password.setValue(a);this.inputFields.rememberPassword.setValue(""!==a);this.populatedSavedLogin=!0};ExtensionLoginDialog.prototype.parseSavedLogin=function(a){switch(a["protected"]){case 0:this.populateSavedLogin(a.password);break;case 1:bg.unprotect_data(a.password,!1,this.createDynamicHandler(function(a){this.populateSavedLogin(a)}));break;case 2:this.populateSavedLogin(bg.lpdec(a.password,bg.AES.hex2bin(bg.SHA256(a.username))))}};
ExtensionLoginDialog.prototype.initialize=function(a){LoginDialog.prototype.initialize.apply(this,arguments);this.inputFields.rememberPassword.getElement().bind("click",function(b){var a=!1,c=function(){a=!0;b.inputFields.rememberPassword.setValue(!0)};return function(){var d=b.inputFields.rememberPassword.getValue();!a&&d?(dialogs.confirmation.open({title:Strings.translateString("Are you sure?"),text:Strings.translateString("Using 'remember password' makes it easier to forget your password and decreases your security if your device is infected or stolen."),
handler:c,onResize:b.data.onResize}),b.inputFields.rememberPassword.setValue(!1)):a=!1}}(this));var c=function(b){return function(a){var c=b.populatedSavedLogin;b.populatedSavedLogin=!1;if(b.data.savedLogins)for(var d=0,f=b.data.savedLogins.length;d<f;++d){var e=b.data.savedLogins[d];if(e.username===a){b.parseSavedLogin(e);break}}c&&!b.populatedSavedLogin&&(b.inputFields.password.clear(),b.inputFields.rememberPassword.clear());a&&bg.localStorage_getItem(bg.SHA256(a)+".noremember")?$("#ExtensionLoginDialogRememberPasswordContainer").hide():
$("#ExtensionLoginDialogRememberPasswordContainer").show()}}(this);this.inputFields.email.onChange(c);this.inputFields.email.inputObject.onChange(c)};ExtensionLoginDialog.prototype.setup=function(){LoginDialog.prototype.setup.apply(this,arguments);bg.get_saved_logins(this.savedLoginCallback);LPPlatform.checkBrowserPasswordManager(this.browserPasswordManagerCallback)};ExtensionLoginDialog.prototype.open=function(a){LoginDialog.prototype.open.call(this,$.extend(a,{defaultData:{rememberEmail:bg.Preferences.get("rememberemail"),
rememberPassword:bg.Preferences.get("rememberpassword"),rememberShowVault:bg.Preferences.get("showvault")}}))};ExtensionLoginDialog.prototype.handleSubmit=function(){var a=null,c=function(b){null===a&&(a=setInterval(function(){"undefined"===typeof VaultState&&bg.getData&&bg.getData({context:"login"});bg.get("lploggedin")&&(clearInterval(a),a=null,b.close())},1E3))};return function(a){a.email=bg.fix_username(a.email);bg.Preferences.set({rememberemail:a.rememberEmail,rememberpassword:a.rememberPassword,
showvault:a.rememberShowVault});a.disablePasswordManager&&bg.disablepasswordmanager(!0);bg.make_lp_key_hash(a.email,a.password,function(b,c){return function(d,f){b.set("g_manual_login",!0);b.LP_do_login(a.email,a.password,a.rememberEmail,a.rememberPassword,null,a.rememberShowVault,d,f);c.data.isPopup&&c.close()}}(bg,this));this.data.isPopup||c(this)}}()})();
