LPTabState=function(){var h={},r=null;LPPlatform.onTabClosed(function(a){delete h[a]});Topics.get(Topics.CLEAR_DATA).subscribe(function(){h={}});var p=function(a,b){b=[].concat(b);var c=b.indexOf(lpmdec_acct(a.password,!0,a,g_shares));if(-1===c&&a.fields&&0<a.fields.length)for(var d=0;d<a.fields.length;++d){var g=a.fields[d];if("password"===g.type&&(c=b.indexOf(lpmdec_acct(g.value,!0,a,g_shares)),-1<c))break}return-1<c?b[c]:null},q=function(){var a=/[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*/g,
b=function(a){if(a=get_ff_translation(a))return new RegExp(a)},c=function(a,c){if(a&&c)return a.test(c.toLowerCase())},d=[function(){var a=function(a,b,d){if(c(b,a.id)||c(a.attributes.name)||c(d,a.label))return!0};return function(c,d,n){d=b("ff_ssn_regexp");n=b("ff_text_ssn_regexp");for(var f=b("ff_cccsc_regexp"),x=b("ff_text_cccsc_regexp"),g=b("ff_securityanswer_regexp"),y=b("ff_captcha_regexp"),m=0;m<c.fields.length;++m){var e=c.fields[m];if(a(e,d,n)||a(e,f,x)||a(e,g)||a(e,y))return!1}}}(),function(a,
c,b){if(1===c.uniquePasswords.length)return b=c.uniquePasswords[0],2===c.passwordsByValue[b].count&&(2===a.fields.length?a.passwordChangeForm=!0:a.createAccountForm=!0),b},function(a,c,b){for(var f in c.passwordsByValue)if(1<c.passwordsByValue[f].count)return 2===c.uniquePasswords.length?(a.passwordChangeForm=!0,a.originalPassword=c.uniquePasswords[0]===f?c.uniquePasswords[1]:c.uniquePasswords[0]):a.createAccountForm=!0,f},function(a,c,b){if(2===c.uniquePasswords.length){a:{b=b.getSites();for(var f=
c.uniquePasswords,d=0;d<b.length;++d){var n=p(b[d],f);if(n){b=n;break a}}b=null}if(b)return a.passwordChangeForm=!0,a.originalPassword=b,c.uniquePasswords[0]===b?c.uniquePasswords[1]:c.uniquePasswords[0]}},function(a,c,b){for(var f in c.passwordsByValue)if(a=c.passwordsByValue[f].field,b=["pw","pass"],k(a.attributes.name,b)||k(a.id,b))return f}],g=function(a,f,d){if(f=b("ff_username_regexp"))for(d=0;d<a.fields.length;++d){var g=a.fields[d];if(c(f,g.label))return g.value}},m=function(a,c,b){for(var d in c.textFieldsByValue)if(a=
c.textFieldsByValue[d].field,k(a.attributes.name,"user")||k(a.id,"user"))return d},e=[g,function(a,c,b){if(1===c.uniqueTextValues.length)return b=c.uniqueTextValues[0],2===c.textFieldsByValue[b].count&&(a.createAccountForm=!0),b},function(a,c,b){for(var d in c.textFieldsByValue)if(1<c.textFieldsByValue[d].count)return a.createAccountForm=!0,d},function(a,c,b){a=a.fields;for(c=1;c<a.length;++c)if("password"===a[c].type&&(b=a[c-1],"password"!==b.type))return b.value},function(a,c,b){for(var d in g_sites)if(-1<
c.uniqueTextValues.indexOf(g_sites[d].unencryptedUsername))return g_sites[d].unencryptedUsername},function(c,b,d){c=[];for(var f in b.textFieldsByValue)(b=f.match(a))&&1===b.length&&c.push(f);if(1===c.length)return c[0]},m],h=function(){var a=function(a,c,b){var d=b[c];"undefined"===typeof d?b[c]={field:a,count:1}:++d.count};return function(c){var b={},d={},f={};c.fields.forEach(function(c){"password"===c.type?a(c,c.value,b):(a(c,c.value,d),a(c,c.type,f))});return{passwordsByValue:b,textFieldsByValue:d,
textFieldsByType:f,uniqueTextValues:Object.keys(d),uniquePasswords:Object.keys(b)}}}(),k=function(c,a){if(c){a=[].concat(a);for(var b=0;b<a.length;++b)if(-1<c.indexOf(a[b]))return!0}return!1},l=function(c,a,b,d){for(var f=null,g=0;g<d.length&&!(f=d[g](c,a,b))&&!1!==f;++g);return f};return function(c,a,b){a.fields=a.fields||[];var f=h(a),k=!1,t=!a.generatedPassword;a.password||(a.password=a.generatedPassword?a.generatedPassword:l(a,f,c,d));a.username=function(){var d=e;b&&b.strict&&(d=[g,m]);var k=
l(a,f,c,d),d=c.getSites().filter(function(a){return u(a,k)});return a.username&&0===d.length&&!a.createAccountForm?a.username:k}();var n=function(){if(a.username&&!a.createAccountForm)for(var c=0;c<a.fields.length;++c){var b=a.fields[c];if(b.value===a.username)return b}return null}();this.submitted=function(a){"boolean"===typeof a&&(t=a);return t};this.succeeded=function(a){"boolean"===typeof a&&(k=a);return k};this.getUsernameField=function(){return n};this.getUsername=function(){return a.username};
this.getPassword=function(){return a.password};this.getFormData=function(){return a};this.getFields=function(){return a.fields.slice()};this.getOriginalPassword=function(){return a.originalPassword};this.isChangePasswordForm=function(){return!0===a.passwordChangeForm};this.isCreateAccountForm=function(){return!0===a.createAccountForm};this.isBasicAuthentication=function(){return!0===a.basicAuthentication};this.shouldSaveFields=function(){return!this.isChangePasswordForm()&&!this.isCreateAccountForm()}}}(),
e=function(a){this.tabID=a.tabID;this.domain=lp_gettld_url(a.tabURL);this.sites=[];this.username=this.usernameField=this.acccountsVersion=null};e.prototype.getSites=function(){if(this.acccountsVersion!==g_local_accts_version){this.sites=[];var a=getsites(this.domain),b;for(b in a)this.sites.push(g_sites[b]);this.acccountsVersion=g_local_accts_version}return this.sites};e.prototype.getFields=function(){var a=[];this.passwordForm&&(a=this.passwordForm.getFields());var b=this.getUsernameField();b&&b.value===
this.getUsername()&&0===a.filter(function(a){return a.name===b.name&&a.value===b.value}).length&&a.unshift(b);return a.filter(function(a){return a.id||a.attributes.name})};e.prototype.getUsernameField=function(){if(!this.usernameField)for(var a in h){var b=h[a];if(b.usernameField&&compare_tlds(b.domain,this.domain)){this.usernameField=b.usernameField;break}}return this.usernameField};e.prototype.setUsernameField=function(a){a&&(this.usernameField=a)};e.prototype.setUsername=function(a){a&&(this.username=
a)};e.prototype.getUsername=function(){!this.username&&this.passwordForm&&(this.username=this.passwordForm.getUsername());if(!this.username)for(var a in h){var b=h[a];if(b.username&&compare_tlds(b.domain,this.domain)){this.username=b.username;break}}return this.username};e.prototype.processPasswordSubmit=function(a,b){this.passwordForm=new q(this,a);this.setUsernameField(this.passwordForm.getUsernameField());this.setUsername(this.passwordForm.getUsername());if(a.generatedPassword)this.generatedPassword=
a.generatedPassword;else LPPlatform.once(LPPlatform.onTransition,function(a){a:{switch(a.transitionType){case "auto_subframe":case "manual_subframe":a=!1;break a}a=-1<a.transitionQualifiers.indexOf("from_address_bar")||-1<a.transitionQualifiers.indexOf("forward_back")}a&&this.clear()},this)};e.prototype.processTextSubmit=function(a,b){var c=new q(this,a,{strict:!0});this.setUsernameField(c.getUsernameField());this.setUsername(c.getUsername())};var u=function(){var a=function(a,b){if(b&&-1<b.indexOf("@")){var c=
b.split("@");return 2===c.length&&a===c[0]}return!1},b=function(c,b){var d;(d=c===b||a(c,b)||a(b,c))||(d=-1<b.indexOf("*")||-1<b.indexOf(String.fromCharCode(8226))?c.length===b.length&&(c[0]===b[0]||c[c.length-1]===b[b.length-1]):!1);return d};return function(a,d){if(d){if(b(a.unencryptedUsername,d))return!0;if(a.fields&&0<a.fields.length)for(var c=0;c<a.fields.length;++c){var m=a.fields[c];switch(m.type){case "text":case "email":case "tel":if(b(lpmdec_acct(m.value,!0,a,g_shares),d))return!0}}}return!1}}();
e.prototype.getMatchingSites=function(){var a=this,b=a.getSites();if(a.getUsername())b=b.filter(function(c){return u(c,a.getUsername())});else{var c=a.passwordForm&&a.passwordForm.getOriginalPassword();c&&(b=b.filter(function(a){return null!==p(a,c)}));0===b.length&&(b=a.getSites())}return b};e.prototype.shouldShowSiteNotification=function(){if(this.passwordForm&&this.passwordForm.succeeded())return this.passwordForm.isChangePasswordForm()?Preferences.get("showChangeNotificationBar"):Preferences.get("showSaveNotificationBar")};
var z=function(){var a=function(a){var c="";a.forEach(function(a){c+=a.formname+"\t"+encodeURIComponent(a.name)+"\t"+encodeURIComponent(crypto_btoa(a.value))+"\t"+encodeURIComponent(a.type)+"\n"});return bin2hex(c)};return function(b,c){if(0<c.length){b.fields=b.fields.concat(c);g_local_accts_version++;rewritelocalfile();var d={data:a(c),ref:url2hex(b.url),updatefields:1,aid:b.aid};b.sharedfolderid&&(d.sharedfolderid=b.sharedfolderid);b.postdata=(new PostParams(d)).toString();b.posturl=base_url+"gm_deliver.php";
b.newvalues=c;updateFieldsFromSubmit(b.postdata,b)}}}(),v=function(a){return{name:a.attributes.name||a.id,type:a.type,value:a.value,formname:""}},A=function(a,b){return b===a.unencryptedUsername?a.username:b===lpmdec_acct(a.password,!0,a,g_shares)?a.password:lpmenc_acct(b,!0,a,g_shares)};e.prototype.addFields=function(a){if(this.getUsername()){var b=this.getFields();a.forEach(function(a){if(a.fields){var c=[];b.forEach(function(b){var d=v(b);0===a.fields.filter(function(c){return c.name===d.name&&
(!a.save_all||c.formname===b.formname)}).length&&c.push({otherfield:a.save_all,name:d.name,type:d.type,value:A(a,b.value),checked:!1,formname:a.save_all?b.formname:"",urid:"0",otherlogin:"0",url:""})});z(a,c)}})}};e.prototype.getSiteNotificationData=function(a){if(this.passwordForm){var b={formSubmitted:this.passwordForm.submitted(),formSucceeded:this.passwordForm.succeeded()};if(this.shouldShowSiteNotification()){var c=this.passwordForm.getFormData(),d=this.getMatchingSites(),g=d.filter(function(a){return null!==
p(a,this.passwordForm.getPassword())},this);if(0<g.length)return this.addFields(g),this.clear({force:!0}),{};b.matchingSites=d.map(function(a){return a.aid});b.defaultData={url:this.passwordForm.shouldSaveFields()?c.url:hostof(c.url),name:this.domain,unencryptedUsername:this.getUsername(),group:g_nofolder_feature_enabled?"":siteCats[this.domain],basic_auth:this.passwordForm.isBasicAuthentication()?"1":"0",realm:c.realm};b.dialogData={password:this.passwordForm.getPassword()};b.matchingSiteSameSubDomain=
1===d.length&&hostof(d[0].url)===hostof(this.passwordForm.getFormData().url);b.sameDomain=compare_tlds(lp_gettld_url(this.passwordForm.getFormData().url),lp_gettld_url(a.tabURL));b.generatedPassword=this.generatedPassword===this.passwordForm.getPassword();this.passwordForm.shouldSaveFields()&&0<this.getFields().length&&(b.dialogData.fields=this.getFields().map(v))}else this.clear();return b}return{}};e.prototype.getFormSubmissionTabState=function(){for(var a=this;a;){if(a.passwordForm)return a;a=
a.previousTabState}return this};e.prototype.getUsernames=function(){return this.getSites().map(function(a){return a.unencryptedUsername})};e.prototype.getSiteNotification=function(){var a=function(a,b,g){var c=a.getUsernames();b.forEachWindow({each:function(b,d){return b.LPContentScriptTools.findText({searches:c,callback:function(b){a.setUsername(b);d()}})},done:g})},b=function(b,d,g){var c=!1,e=LPTabs.get({tabID:b.tabID}),h=function(){if(b.passwordForm&&(b.passwordForm.succeeded()||b.passwordForm.succeeded(!c),
b.passwordForm.succeeded()&&!b.passwordForm.getUsername()&&0<b.getSites().length)){a(b,e,g);return}g()};if(d)(d=e.getFrame(d.frameID))&&d.LPSiteNotification.formExists(b.passwordForm.getFormData(),function(a){c=a;h()});else if(b.passwordForm.getFormData().top)e.getTop().LPSiteNotification.formExists(b.passwordForm.getFormData(),function(a){c=a;h()});else e.onFramesLoaded(function(){e.forEachFrame({each:function(a,d){return a.LPSiteNotification.formExists(b.passwordForm.getFormData(),function(a){c=
c||a;d()})},done:h})})};return function(a,d){if(a.callback){var c=this.getFormSubmissionTabState(),e=function(){a.callback(c.getSiteNotificationData(d))};if(c.passwordForm&&c.passwordForm.getPassword())if(c.domain!==this.domain||c.passwordForm.isBasicAuthentication())c.passwordForm.succeeded(!0);else{b(c,a.source,e);return}e()}}}();e.prototype.clear=function(a){var b=a&&a.force,c=!0;this.previousTabState&&(c=this.previousTabState.clear(a))&&delete this.previousTabState;this.passwordForm&&(this.passwordForm.getPassword()===
this.generatedPassword&&(this.passwordForm.submitted(!1),c=!1),c||b)&&(delete this.passwordForm,delete this.generatedPassword);return c};e.prototype.processBasicAuthentication=function(a){this.passwordForm=new q(this,{basicAuthentication:!0,url:a.url,realm:a.realm,username:a.username,password:a.password})};var w=function(a){if(!lploggedin)return!1;var b=lp_gettld_url(a.tabURL);if(LPContentScriptFeatures.new_save_site)return!hasNeverSave(a.tabURL,b)&&!lp_url_is_lastpass(a.tabURL)&&!lp_url_is_lastpassext(a.tabURL);
a=IntroTutorial.getState();return a.enabled&&a.domain===b},l=function(a,b){if(a){if(w(a)){var c=h[a.tabID];if(!c||!compare_tlds(c.domain,lp_gettld_url(a.tabURL))){var d=h[a.tabID]=new e(a);d.previousTabState=c;c=d}b(c)}}else LPPlatform.getCurrentTab(function(a){l(a.tabDetails,b)})};return{getSiteNotification:function(a,b){l(b,function(c){c.getSiteNotification(a,b)})},clear:function(a,b){l(b,function(b){b.clear(a)})},processPasswordSubmit:function(a,b){l(b,function(c){c.processPasswordSubmit(a.formData,
b);c.getSiteNotification({callback:a.callback,source:b},b)})},processTextSubmit:function(a,b){l(b,function(c){c.processTextSubmit(a,b)})},processBasicAuthentication:function(a,b){l(b,function(b){b.processBasicAuthentication(a)})},getState:function(a,b){var c={enabled:w(b)};c.enabled?l(b,function(b){c.usernames=b.getUsernames();c.formSubmittedFrame=b.passwordForm&&!b.passwordForm.getFormData().top;a(c)}):a(c)},setCopiedGeneratedPassword:function(a){r=a},getCopiedGeneratedPassword:function(a){a(r)}}}();
