# Set PATH, MANPATH, etc., for Homebrew.
eval "$(/opt/homebrew/bin/brew shellenv)"

# Created by `pipx` on 2024-10-04 19:23:08
export PATH="$PATH:/Users/zakaria/.local/bin"
source "/Users/zakaria/deps/skia/third_party/externals/emsdk/emsdk_env.sh"
