# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH


# Add Doom binary to PATH
# export PATH="$HOME/.config/emacs.d/bin:$PATH"
# export PATH="$PATH:$HOME/Library/Python/3.9/bin/"
# export PATH="$PATH:$HOME/.cargo/bin"
# export PATH="$PATH:/usr/local/smlnj/bin"

# SET INFORPATH TODO: Verify why I need this and add comment to clarify
export INFOPATH=$INFOPATH:/usr/share/info

# Aliases
alias ls='ls --color=auto'
alias ll='ls -lah --color=auto'
alias grep='grep --color=auto'
alias ec="$EDITOR $HOME/.zshrc" # edit .zshrc
alias sc="source $HOME/.zshrc"  # reload zsh configuration
alias cats='highlight -O xterm256 -s bipolar'
alias tmux="TERM=screen-256color-bce tmux"
alias smlnj="rlwrap sml"

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#ZSH_THEME="robbyrussell"
ZSH_THEME="agnoster"

AGNOSTER_PROMPT_SEGMENTS=(prompt_status prompt_context prompt_virtualenv prompt_dir prompt_git prompt_end)

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
#
# This what what I had at OSEDEA: plugins=(git docker aws python direnv)
plugins=(git docker python)

source $ZSH/oh-my-zsh.sh


# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
alias zshconfig="nvim ~/.zshrc"
alias ohmyzsh="nvim ~/.oh-my-zsh"

#export NVM_DIR="$HOME/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
#export PATH="/opt/homebrew/opt/libpq/bin:$PATH"

# I added this because I need to use ruby 3.3.x to build emacs using
# build-emacs-for-macos (https://github.com/jimeh/build-emacs-for-macos)

export PATH="/opt/homebrew/opt/ruby/bin:$PATH"

#export PATH="$HOME/.local/Emacs.app/Contents/MacOS/bin:$PATH"
#export PATH="$HOME/.local/Emacs/Emacs.app/Contents/MacOS/bin:$PATH"
#export PATH="$HOME/.emacs.d/bin:$PATH"

# This to make Emacs launch from terminal
if [ -d "/Applications/Emacs.app/Contents/MacOS/bin" ]; then
  export PATH="/Applications/Emacs.app/Contents/MacOS/bin:$PATH"
fi

# Created by `pipx` on 2024-10-04 19:23:08
#export PATH="$PATH:/Users/zakaria/.local/bin"


# BEGIN opam configuration
# This is useful if you're using opam as it adds:
#   - the correct directories to the PATH
#   - auto-completion for the opam binary
# This section can be safely removed at any time if needed.
#[[ ! -r '/Users/zakaria/.opam/opam-init/init.zsh' ]] || source '/Users/zakaria/.opam/opam-init/init.zsh' > /dev/null 2> /dev/null
# END opam configuration

# TODO: Check this out
# . "$HOME/.local/bin/env"

# Awesome Node Managerment fnm
FNM_PATH="/Users/zakaria.soliman/Library/Application Support/fnm"
if [ -d "$FNM_PATH" ]; then
  export PATH="/Users/zakaria.soliman/Library/Application Support/fnm:$PATH"
  eval "`fnm env`"
fi

# Config for AIDER agentic AI
export OPENAI_API_BASE=https://api.githubcopilot.com
export OPENAI_BASE_URL=https://api.githubcopilot.com
export OPENAI_API_KEY=''

prompt_dir() {
        prompt_segment blue $CURRENT_FG '%c'
}

prompt_context() {
  # Custom (Random emoji)
  emojis=("⚡️" "🔥" "💀" "👑" "😎" "🐸" "🐵"  "🚀" "💡" "🎉" "🔑" "🚦" "🌙")
  RAND_EMOJI_N=$(( $RANDOM % ${#emojis[@]} + 1))
  prompt_segment black default "${emojis[$RAND_EMOJI_N]} "
}


#export PYENV_ROOT="$HOME/.pyenv"
#[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
#eval "$(pyenv init - zsh)"
#
#eval "$(pyenv virtualenv-init -)"

# eval "$(direnv hook zsh)"

# TODO:: Check if best to add this to zprofile, zshenv or zshrc and if it will break MacOS unix utils
# Commands also provided by macOS and the commands dir, dircolors, vdir have been installed with the prefix "g".
# If you need to use these commands with their normal names, you can add a "gnubin" directory to your PATH with:
export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
#  PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"

# fnm
FNM_PATH="/opt/homebrew/opt/fnm/bin"
if [ -d "$FNM_PATH" ]; then
  eval "`fnm env`"
  eval "$(fnm env --use-on-cd --shell zsh)"
fi

# For CLI completions
# Where to find them:
fpath+=(~/.zsh/completions)

#To ensure Zsh recognizes the new completion script, you need to reinitialize the completion system. This is typically done by running compinit
autoload -Uz compinit
compinit
